fail_fast: true

repos:
  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [python]
      # args: ["--check-only"]
    - id: black
      name: black
      entry: poetry run black
      language: system
      require_serial: true
      types: [python]
      # args: ["--check"]
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
      require_serial: true
    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      args: ["--explicit-package-bases"]
      types: [python]
      require_serial: true
      verbose: true

